branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false
