name: Manual NPM Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g. 1.0.4)'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Configure NPM
        run: |
          bun config set //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
          bun config list
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: bun install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Verify NPM Authentication
        run: bun whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          bun version ${{ github.event.inputs.version }} --no-git-tag-version
          git add package.json
          git commit -m "chore: bump version to ${{ github.event.inputs.version }}"
          git push

      - name: Build
        run: bun run build

      - name: Publish to NPM
        run: bun publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
